var tree = [["PantaRei",,"",
                [["OAuth2",,"",
                [["Controller","PantaRei\/OAuth2\/Controller.html","",
                [["AuthorizeController","PantaRei\/OAuth2\/Controller\/AuthorizeController.html","",
                [        ]],["ResourceController","PantaRei\/OAuth2\/Controller\/ResourceController.html","",
                [        ]],["TokenController","PantaRei\/OAuth2\/Controller\/TokenController.html","",
                [        ]]        ]],["EventListener","PantaRei\/OAuth2\/EventListener.html","",
                [["ExceptionListener","PantaRei\/OAuth2\/EventListener\/ExceptionListener.html","",
                [        ]]        ]],["Exception","PantaRei\/OAuth2\/Exception.html","",
                [["AccessDeniedException","PantaRei\/OAuth2\/Exception\/AccessDeniedException.html"," < LogicException",
                [        ]],["ExceptionInterface","PantaRei\/OAuth2\/Exception\/ExceptionInterface.html","",
                [        ]],["InvalidClientException","PantaRei\/OAuth2\/Exception\/InvalidClientException.html"," < InvalidArgumentException",
                [        ]],["InvalidGrantException","PantaRei\/OAuth2\/Exception\/InvalidGrantException.html"," < InvalidArgumentException",
                [        ]],["InvalidRequestException","PantaRei\/OAuth2\/Exception\/InvalidRequestException.html"," < InvalidArgumentException",
                [        ]],["InvalidScopeException","PantaRei\/OAuth2\/Exception\/InvalidScopeException.html"," < InvalidArgumentException",
                [        ]],["ServerErrorException","PantaRei\/OAuth2\/Exception\/ServerErrorException.html"," < LogicException",
                [        ]],["TemporarilyUnavailableException","PantaRei\/OAuth2\/Exception\/TemporarilyUnavailableException.html"," < LogicException",
                [        ]],["UnauthorizedClientException","PantaRei\/OAuth2\/Exception\/UnauthorizedClientException.html"," < LogicException",
                [        ]],["UnsupportedGrantTypeException","PantaRei\/OAuth2\/Exception\/UnsupportedGrantTypeException.html"," < InvalidArgumentException",
                [        ]],["UnsupportedResponseTypeException","PantaRei\/OAuth2\/Exception\/UnsupportedResponseTypeException.html"," < InvalidArgumentException",
                [        ]]        ]],["GrantType","PantaRei\/OAuth2\/GrantType.html","",
                [["AbstractGrantTypeHandler","PantaRei\/OAuth2\/GrantType\/AbstractGrantTypeHandler.html","",
                [        ]],["AuthorizationCodeGrantTypeHandler","PantaRei\/OAuth2\/GrantType\/AuthorizationCodeGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["ClientCredentialsGrantTypeHandler","PantaRei\/OAuth2\/GrantType\/ClientCredentialsGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["GrantTypeHandlerFactory","PantaRei\/OAuth2\/GrantType\/GrantTypeHandlerFactory.html","",
                [        ]],["GrantTypeHandlerFactoryInterface","PantaRei\/OAuth2\/GrantType\/GrantTypeHandlerFactoryInterface.html","",
                [        ]],["GrantTypeHandlerInterface","PantaRei\/OAuth2\/GrantType\/GrantTypeHandlerInterface.html","",
                [        ]],["PasswordGrantTypeHandler","PantaRei\/OAuth2\/GrantType\/PasswordGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["RefreshTokenGrantTypeHandler","PantaRei\/OAuth2\/GrantType\/RefreshTokenGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]]        ]],["Model","PantaRei\/OAuth2\/Model.html","",
                [["AccessTokenInterface","PantaRei\/OAuth2\/Model\/AccessTokenInterface.html","",
                [        ]],["AccessTokenManagerInterface","PantaRei\/OAuth2\/Model\/AccessTokenManagerInterface.html","",
                [        ]],["AuthorizeInterface","PantaRei\/OAuth2\/Model\/AuthorizeInterface.html","",
                [        ]],["AuthorizeManagerInterface","PantaRei\/OAuth2\/Model\/AuthorizeManagerInterface.html","",
                [        ]],["ClientInterface","PantaRei\/OAuth2\/Model\/ClientInterface.html","",
                [        ]],["ClientManagerInterface","PantaRei\/OAuth2\/Model\/ClientManagerInterface.html","",
                [        ]],["CodeInterface","PantaRei\/OAuth2\/Model\/CodeInterface.html","",
                [        ]],["CodeManagerInterface","PantaRei\/OAuth2\/Model\/CodeManagerInterface.html","",
                [        ]],["ModelInterface","PantaRei\/OAuth2\/Model\/ModelInterface.html","",
                [        ]],["ModelManagerFactoryInterface","PantaRei\/OAuth2\/Model\/ModelManagerFactoryInterface.html","",
                [        ]],["ModelManagerInterface","PantaRei\/OAuth2\/Model\/ModelManagerInterface.html","",
                [        ]],["RefreshTokenInterface","PantaRei\/OAuth2\/Model\/RefreshTokenInterface.html","",
                [        ]],["RefreshTokenManagerInterface","PantaRei\/OAuth2\/Model\/RefreshTokenManagerInterface.html","",
                [        ]],["ScopeInterface","PantaRei\/OAuth2\/Model\/ScopeInterface.html","",
                [        ]],["ScopeManagerInterface","PantaRei\/OAuth2\/Model\/ScopeManagerInterface.html","",
                [        ]]        ]],["Provider","PantaRei\/OAuth2\/Provider.html","",
                [["OAuth2ServiceProvider","PantaRei\/OAuth2\/Provider\/OAuth2ServiceProvider.html","",
                [        ]]        ]],["ResponseType","PantaRei\/OAuth2\/ResponseType.html","",
                [["AbstractResponseTypeHandler","PantaRei\/OAuth2\/ResponseType\/AbstractResponseTypeHandler.html","",
                [        ]],["CodeResponseTypeHandler","PantaRei\/OAuth2\/ResponseType\/CodeResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]],["ResponseTypeHandlerFactory","PantaRei\/OAuth2\/ResponseType\/ResponseTypeHandlerFactory.html","",
                [        ]],["ResponseTypeHandlerFactoryInterface","PantaRei\/OAuth2\/ResponseType\/ResponseTypeHandlerFactoryInterface.html","",
                [        ]],["ResponseTypeHandlerInterface","PantaRei\/OAuth2\/ResponseType\/ResponseTypeHandlerInterface.html","",
                [        ]],["TokenResponseTypeHandler","PantaRei\/OAuth2\/ResponseType\/TokenResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]]        ]],["Security",,"",
                [["Authentication",,"",
                [["Provider","PantaRei\/OAuth2\/Security\/Authentication\/Provider.html","",
                [["ResourceProvider","PantaRei\/OAuth2\/Security\/Authentication\/Provider\/ResourceProvider.html","",
                [        ]],["TokenProvider","PantaRei\/OAuth2\/Security\/Authentication\/Provider\/TokenProvider.html","",
                [        ]]        ]],["Token","PantaRei\/OAuth2\/Security\/Authentication\/Token.html","",
                [["AccessToken","PantaRei\/OAuth2\/Security\/Authentication\/Token\/AccessToken.html"," < AbstractToken",
                [        ]],["ClientToken","PantaRei\/OAuth2\/Security\/Authentication\/Token\/ClientToken.html"," < AbstractToken",
                [        ]]        ]]        ]],["Firewall","PantaRei\/OAuth2\/Security\/Firewall.html","",
                [["ResourceListener","PantaRei\/OAuth2\/Security\/Firewall\/ResourceListener.html","",
                [        ]],["TokenListener","PantaRei\/OAuth2\/Security\/Firewall\/TokenListener.html","",
                [        ]]        ]]        ]],["TokenType","PantaRei\/OAuth2\/TokenType.html","",
                [["BearerTokenTypeHandler","PantaRei\/OAuth2\/TokenType\/BearerTokenTypeHandler.html","",
                [        ]],["MacTokenTypeHandler","PantaRei\/OAuth2\/TokenType\/MacTokenTypeHandler.html","",
                [        ]],["TokenTypeHandlerFactory","PantaRei\/OAuth2\/TokenType\/TokenTypeHandlerFactory.html","",
                [        ]],["TokenTypeHandlerFactoryInterface","PantaRei\/OAuth2\/TokenType\/TokenTypeHandlerFactoryInterface.html","",
                [        ]],["TokenTypeHandlerInterface","PantaRei\/OAuth2\/TokenType\/TokenTypeHandlerInterface.html","",
                [        ]]        ]],["Util","PantaRei\/OAuth2\/Util.html","",
                [["Filter","PantaRei\/OAuth2\/Util\/Filter.html","",
                [        ]],["JsonResponse","PantaRei\/OAuth2\/Util\/JsonResponse.html"," < JsonResponse",
                [        ]],["RedirectResponse","PantaRei\/OAuth2\/Util\/RedirectResponse.html"," < RedirectResponse",
                [        ]]        ]]        ]]        ]],["Pantarei",,"",
                [["OAuth2",,"",
                [["Controller","Pantarei\/OAuth2\/Controller.html","",
                [["AuthorizeController","Pantarei\/OAuth2\/Controller\/AuthorizeController.html","",
                [        ]],["ResourceController","Pantarei\/OAuth2\/Controller\/ResourceController.html","",
                [        ]],["TokenController","Pantarei\/OAuth2\/Controller\/TokenController.html","",
                [        ]]        ]],["EventListener","Pantarei\/OAuth2\/EventListener.html","",
                [["ExceptionListener","Pantarei\/OAuth2\/EventListener\/ExceptionListener.html","",
                [        ]]        ]],["Exception","Pantarei\/OAuth2\/Exception.html","",
                [["AccessDeniedException","Pantarei\/OAuth2\/Exception\/AccessDeniedException.html"," < LogicException",
                [        ]],["ExceptionInterface","Pantarei\/OAuth2\/Exception\/ExceptionInterface.html","",
                [        ]],["InvalidClientException","Pantarei\/OAuth2\/Exception\/InvalidClientException.html"," < InvalidArgumentException",
                [        ]],["InvalidGrantException","Pantarei\/OAuth2\/Exception\/InvalidGrantException.html"," < InvalidArgumentException",
                [        ]],["InvalidRequestException","Pantarei\/OAuth2\/Exception\/InvalidRequestException.html"," < InvalidArgumentException",
                [        ]],["InvalidScopeException","Pantarei\/OAuth2\/Exception\/InvalidScopeException.html"," < InvalidArgumentException",
                [        ]],["ServerErrorException","Pantarei\/OAuth2\/Exception\/ServerErrorException.html"," < LogicException",
                [        ]],["TemporarilyUnavailableException","Pantarei\/OAuth2\/Exception\/TemporarilyUnavailableException.html"," < LogicException",
                [        ]],["UnauthorizedClientException","Pantarei\/OAuth2\/Exception\/UnauthorizedClientException.html"," < LogicException",
                [        ]],["UnsupportedGrantTypeException","Pantarei\/OAuth2\/Exception\/UnsupportedGrantTypeException.html"," < InvalidArgumentException",
                [        ]],["UnsupportedResponseTypeException","Pantarei\/OAuth2\/Exception\/UnsupportedResponseTypeException.html"," < InvalidArgumentException",
                [        ]]        ]],["GrantType","Pantarei\/OAuth2\/GrantType.html","",
                [["AbstractGrantTypeHandler","Pantarei\/OAuth2\/GrantType\/AbstractGrantTypeHandler.html","",
                [        ]],["AuthorizationCodeGrantTypeHandler","Pantarei\/OAuth2\/GrantType\/AuthorizationCodeGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["ClientCredentialsGrantTypeHandler","Pantarei\/OAuth2\/GrantType\/ClientCredentialsGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["GrantTypeHandlerFactory","Pantarei\/OAuth2\/GrantType\/GrantTypeHandlerFactory.html","",
                [        ]],["GrantTypeHandlerFactoryInterface","Pantarei\/OAuth2\/GrantType\/GrantTypeHandlerFactoryInterface.html","",
                [        ]],["GrantTypeHandlerInterface","Pantarei\/OAuth2\/GrantType\/GrantTypeHandlerInterface.html","",
                [        ]],["PasswordGrantTypeHandler","Pantarei\/OAuth2\/GrantType\/PasswordGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["RefreshTokenGrantTypeHandler","Pantarei\/OAuth2\/GrantType\/RefreshTokenGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]]        ]],["Model","Pantarei\/OAuth2\/Model.html","",
                [["AccessTokenInterface","Pantarei\/OAuth2\/Model\/AccessTokenInterface.html","",
                [        ]],["AccessTokenManagerInterface","Pantarei\/OAuth2\/Model\/AccessTokenManagerInterface.html","",
                [        ]],["AuthorizeInterface","Pantarei\/OAuth2\/Model\/AuthorizeInterface.html","",
                [        ]],["AuthorizeManagerInterface","Pantarei\/OAuth2\/Model\/AuthorizeManagerInterface.html","",
                [        ]],["ClientInterface","Pantarei\/OAuth2\/Model\/ClientInterface.html","",
                [        ]],["ClientManagerInterface","Pantarei\/OAuth2\/Model\/ClientManagerInterface.html","",
                [        ]],["CodeInterface","Pantarei\/OAuth2\/Model\/CodeInterface.html","",
                [        ]],["CodeManagerInterface","Pantarei\/OAuth2\/Model\/CodeManagerInterface.html","",
                [        ]],["ModelInterface","Pantarei\/OAuth2\/Model\/ModelInterface.html","",
                [        ]],["ModelManagerFactoryInterface","Pantarei\/OAuth2\/Model\/ModelManagerFactoryInterface.html","",
                [        ]],["ModelManagerInterface","Pantarei\/OAuth2\/Model\/ModelManagerInterface.html","",
                [        ]],["RefreshTokenInterface","Pantarei\/OAuth2\/Model\/RefreshTokenInterface.html","",
                [        ]],["RefreshTokenManagerInterface","Pantarei\/OAuth2\/Model\/RefreshTokenManagerInterface.html","",
                [        ]],["ScopeInterface","Pantarei\/OAuth2\/Model\/ScopeInterface.html","",
                [        ]],["ScopeManagerInterface","Pantarei\/OAuth2\/Model\/ScopeManagerInterface.html","",
                [        ]]        ]],["Provider","Pantarei\/OAuth2\/Provider.html","",
                [["OAuth2ServiceProvider","Pantarei\/OAuth2\/Provider\/OAuth2ServiceProvider.html","",
                [        ]]        ]],["ResponseType","Pantarei\/OAuth2\/ResponseType.html","",
                [["AbstractResponseTypeHandler","Pantarei\/OAuth2\/ResponseType\/AbstractResponseTypeHandler.html","",
                [        ]],["CodeResponseTypeHandler","Pantarei\/OAuth2\/ResponseType\/CodeResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]],["ResponseTypeHandlerFactory","Pantarei\/OAuth2\/ResponseType\/ResponseTypeHandlerFactory.html","",
                [        ]],["ResponseTypeHandlerFactoryInterface","Pantarei\/OAuth2\/ResponseType\/ResponseTypeHandlerFactoryInterface.html","",
                [        ]],["ResponseTypeHandlerInterface","Pantarei\/OAuth2\/ResponseType\/ResponseTypeHandlerInterface.html","",
                [        ]],["TokenResponseTypeHandler","Pantarei\/OAuth2\/ResponseType\/TokenResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]]        ]],["Security",,"",
                [["Authentication",,"",
                [["Provider","Pantarei\/OAuth2\/Security\/Authentication\/Provider.html","",
                [["ResourceProvider","Pantarei\/OAuth2\/Security\/Authentication\/Provider\/ResourceProvider.html","",
                [        ]],["TokenProvider","Pantarei\/OAuth2\/Security\/Authentication\/Provider\/TokenProvider.html","",
                [        ]]        ]],["Token","Pantarei\/OAuth2\/Security\/Authentication\/Token.html","",
                [["AccessToken","Pantarei\/OAuth2\/Security\/Authentication\/Token\/AccessToken.html"," < AbstractToken",
                [        ]],["ClientToken","Pantarei\/OAuth2\/Security\/Authentication\/Token\/ClientToken.html"," < AbstractToken",
                [        ]]        ]]        ]],["Firewall","Pantarei\/OAuth2\/Security\/Firewall.html","",
                [["ResourceListener","Pantarei\/OAuth2\/Security\/Firewall\/ResourceListener.html","",
                [        ]],["TokenListener","Pantarei\/OAuth2\/Security\/Firewall\/TokenListener.html","",
                [        ]]        ]]        ]],["TokenType","Pantarei\/OAuth2\/TokenType.html","",
                [["BearerTokenTypeHandler","Pantarei\/OAuth2\/TokenType\/BearerTokenTypeHandler.html","",
                [        ]],["MacTokenTypeHandler","Pantarei\/OAuth2\/TokenType\/MacTokenTypeHandler.html","",
                [        ]],["TokenTypeHandlerFactory","Pantarei\/OAuth2\/TokenType\/TokenTypeHandlerFactory.html","",
                [        ]],["TokenTypeHandlerFactoryInterface","Pantarei\/OAuth2\/TokenType\/TokenTypeHandlerFactoryInterface.html","",
                [        ]],["TokenTypeHandlerInterface","Pantarei\/OAuth2\/TokenType\/TokenTypeHandlerInterface.html","",
                [        ]]        ]],["Util","Pantarei\/OAuth2\/Util.html","",
                [["Filter","Pantarei\/OAuth2\/Util\/Filter.html","",
                [        ]],["JsonResponse","Pantarei\/OAuth2\/Util\/JsonResponse.html"," < JsonResponse",
                [        ]],["RedirectResponse","Pantarei\/OAuth2\/Util\/RedirectResponse.html"," < RedirectResponse",
                [        ]]        ]]        ]]        ]]        ]

