var tree = [["Pantarei",,"",
                [["Oauth2",,"",
                [["Controller","Pantarei\/Oauth2\/Controller.html","",
                [["AuthorizeController","Pantarei\/Oauth2\/Controller\/AuthorizeController.html","",
                [        ]],["TokenController","Pantarei\/Oauth2\/Controller\/TokenController.html","",
                [        ]]        ]],["Exception","Pantarei\/Oauth2\/Exception.html","",
                [["AccessDeniedException","Pantarei\/Oauth2\/Exception\/AccessDeniedException.html"," < LogicException",
                [        ]],["ExceptionInterface","Pantarei\/Oauth2\/Exception\/ExceptionInterface.html","",
                [        ]],["InvalidClientException","Pantarei\/Oauth2\/Exception\/InvalidClientException.html"," < InvalidArgumentException",
                [        ]],["InvalidGrantException","Pantarei\/Oauth2\/Exception\/InvalidGrantException.html"," < InvalidArgumentException",
                [        ]],["InvalidRequestException","Pantarei\/Oauth2\/Exception\/InvalidRequestException.html"," < InvalidArgumentException",
                [        ]],["InvalidScopeException","Pantarei\/Oauth2\/Exception\/InvalidScopeException.html"," < InvalidArgumentException",
                [        ]],["ServerErrorException","Pantarei\/Oauth2\/Exception\/ServerErrorException.html"," < LogicException",
                [        ]],["TemporarilyUnavailableException","Pantarei\/Oauth2\/Exception\/TemporarilyUnavailableException.html"," < LogicException",
                [        ]],["UnauthorizedClientException","Pantarei\/Oauth2\/Exception\/UnauthorizedClientException.html"," < LogicException",
                [        ]],["UnsupportedGrantTypeException","Pantarei\/Oauth2\/Exception\/UnsupportedGrantTypeException.html"," < InvalidArgumentException",
                [        ]],["UnsupportedResponseTypeException","Pantarei\/Oauth2\/Exception\/UnsupportedResponseTypeException.html"," < InvalidArgumentException",
                [        ]]        ]],["GrantType","Pantarei\/Oauth2\/GrantType.html","",
                [["AbstractGrantTypeHandler","Pantarei\/Oauth2\/GrantType\/AbstractGrantTypeHandler.html","",
                [        ]],["AuthorizationCodeGrantTypeHandler","Pantarei\/Oauth2\/GrantType\/AuthorizationCodeGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["ClientCredentialsGrantTypeHandler","Pantarei\/Oauth2\/GrantType\/ClientCredentialsGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["GrantTypeHandlerFactory","Pantarei\/Oauth2\/GrantType\/GrantTypeHandlerFactory.html","",
                [        ]],["GrantTypeHandlerFactoryInterface","Pantarei\/Oauth2\/GrantType\/GrantTypeHandlerFactoryInterface.html","",
                [        ]],["GrantTypeHandlerInterface","Pantarei\/Oauth2\/GrantType\/GrantTypeHandlerInterface.html","",
                [        ]],["PasswordGrantTypeHandler","Pantarei\/Oauth2\/GrantType\/PasswordGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["RefreshTokenGrantTypeHandler","Pantarei\/Oauth2\/GrantType\/RefreshTokenGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]]        ]],["Model","Pantarei\/Oauth2\/Model.html","",
                [["AccessTokenInterface","Pantarei\/Oauth2\/Model\/AccessTokenInterface.html","",
                [        ]],["AccessTokenManagerInterface","Pantarei\/Oauth2\/Model\/AccessTokenManagerInterface.html","",
                [        ]],["AuthorizeInterface","Pantarei\/Oauth2\/Model\/AuthorizeInterface.html","",
                [        ]],["AuthorizeManagerInterface","Pantarei\/Oauth2\/Model\/AuthorizeManagerInterface.html","",
                [        ]],["ClientInterface","Pantarei\/Oauth2\/Model\/ClientInterface.html","",
                [        ]],["ClientManagerInterface","Pantarei\/Oauth2\/Model\/ClientManagerInterface.html","",
                [        ]],["CodeInterface","Pantarei\/Oauth2\/Model\/CodeInterface.html","",
                [        ]],["CodeManagerInterface","Pantarei\/Oauth2\/Model\/CodeManagerInterface.html","",
                [        ]],["ModelInterface","Pantarei\/Oauth2\/Model\/ModelInterface.html","",
                [        ]],["ModelManagerFactoryInterface","Pantarei\/Oauth2\/Model\/ModelManagerFactoryInterface.html","",
                [        ]],["ModelManagerInterface","Pantarei\/Oauth2\/Model\/ModelManagerInterface.html","",
                [        ]],["RefreshTokenInterface","Pantarei\/Oauth2\/Model\/RefreshTokenInterface.html","",
                [        ]],["RefreshTokenManagerInterface","Pantarei\/Oauth2\/Model\/RefreshTokenManagerInterface.html","",
                [        ]],["ScopeInterface","Pantarei\/Oauth2\/Model\/ScopeInterface.html","",
                [        ]],["ScopeManagerInterface","Pantarei\/Oauth2\/Model\/ScopeManagerInterface.html","",
                [        ]]        ]],["Provider","Pantarei\/Oauth2\/Provider.html","",
                [["Oauth2ServiceProvider","Pantarei\/Oauth2\/Provider\/Oauth2ServiceProvider.html","",
                [        ]]        ]],["ResponseType","Pantarei\/Oauth2\/ResponseType.html","",
                [["AbstractResponseTypeHandler","Pantarei\/Oauth2\/ResponseType\/AbstractResponseTypeHandler.html","",
                [        ]],["CodeResponseTypeHandler","Pantarei\/Oauth2\/ResponseType\/CodeResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]],["ResponseTypeHandlerFactory","Pantarei\/Oauth2\/ResponseType\/ResponseTypeHandlerFactory.html","",
                [        ]],["ResponseTypeHandlerFactoryInterface","Pantarei\/Oauth2\/ResponseType\/ResponseTypeHandlerFactoryInterface.html","",
                [        ]],["ResponseTypeHandlerInterface","Pantarei\/Oauth2\/ResponseType\/ResponseTypeHandlerInterface.html","",
                [        ]],["TokenResponseTypeHandler","Pantarei\/Oauth2\/ResponseType\/TokenResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]]        ]],["Security",,"",
                [["Authentication",,"",
                [["Provider","Pantarei\/Oauth2\/Security\/Authentication\/Provider.html","",
                [["ResourceProvider","Pantarei\/Oauth2\/Security\/Authentication\/Provider\/ResourceProvider.html","",
                [        ]],["TokenProvider","Pantarei\/Oauth2\/Security\/Authentication\/Provider\/TokenProvider.html","",
                [        ]]        ]],["Token","Pantarei\/Oauth2\/Security\/Authentication\/Token.html","",
                [["AccessToken","Pantarei\/Oauth2\/Security\/Authentication\/Token\/AccessToken.html"," < AbstractToken",
                [        ]],["ClientToken","Pantarei\/Oauth2\/Security\/Authentication\/Token\/ClientToken.html"," < AbstractToken",
                [        ]]        ]]        ]],["Firewall","Pantarei\/Oauth2\/Security\/Firewall.html","",
                [["ResourceListener","Pantarei\/Oauth2\/Security\/Firewall\/ResourceListener.html","",
                [        ]],["TokenListener","Pantarei\/Oauth2\/Security\/Firewall\/TokenListener.html","",
                [        ]]        ]]        ]],["TokenType","Pantarei\/Oauth2\/TokenType.html","",
                [["BearerTokenTypeHandler","Pantarei\/Oauth2\/TokenType\/BearerTokenTypeHandler.html","",
                [        ]],["MacTokenTypeHandler","Pantarei\/Oauth2\/TokenType\/MacTokenTypeHandler.html","",
                [        ]],["TokenTypeHandlerFactory","Pantarei\/Oauth2\/TokenType\/TokenTypeHandlerFactory.html","",
                [        ]],["TokenTypeHandlerFactoryInterface","Pantarei\/Oauth2\/TokenType\/TokenTypeHandlerFactoryInterface.html","",
                [        ]],["TokenTypeHandlerInterface","Pantarei\/Oauth2\/TokenType\/TokenTypeHandlerInterface.html","",
                [        ]]        ]],["Util","Pantarei\/Oauth2\/Util.html","",
                [["Filter","Pantarei\/Oauth2\/Util\/Filter.html","",
                [        ]],["JsonResponse","Pantarei\/Oauth2\/Util\/JsonResponse.html"," < JsonResponse",
                [        ]],["RedirectResponse","Pantarei\/Oauth2\/Util\/RedirectResponse.html"," < RedirectResponse",
                [        ]]        ]]        ]]        ]]        ]

