var tree = [["AuthBucket",,"",
                [["OAuth2",,"",
                [["Controller","AuthBucket\/OAuth2\/Controller.html","",
                [["AuthorizeController","AuthBucket\/OAuth2\/Controller\/AuthorizeController.html","",
                [        ]],["DebugController","AuthBucket\/OAuth2\/Controller\/DebugController.html","",
                [        ]],["ModelController","AuthBucket\/OAuth2\/Controller\/ModelController.html","",
                [        ]],["TokenController","AuthBucket\/OAuth2\/Controller\/TokenController.html","",
                [        ]]        ]],["EventListener","AuthBucket\/OAuth2\/EventListener.html","",
                [["ExceptionListener","AuthBucket\/OAuth2\/EventListener\/ExceptionListener.html","",
                [        ]]        ]],["Exception","AuthBucket\/OAuth2\/Exception.html","",
                [["AccessDeniedException","AuthBucket\/OAuth2\/Exception\/AccessDeniedException.html"," < LogicException",
                [        ]],["ExceptionInterface","AuthBucket\/OAuth2\/Exception\/ExceptionInterface.html","",
                [        ]],["InvalidClientException","AuthBucket\/OAuth2\/Exception\/InvalidClientException.html"," < InvalidArgumentException",
                [        ]],["InvalidGrantException","AuthBucket\/OAuth2\/Exception\/InvalidGrantException.html"," < InvalidArgumentException",
                [        ]],["InvalidRequestException","AuthBucket\/OAuth2\/Exception\/InvalidRequestException.html"," < InvalidArgumentException",
                [        ]],["InvalidScopeException","AuthBucket\/OAuth2\/Exception\/InvalidScopeException.html"," < InvalidArgumentException",
                [        ]],["ServerErrorException","AuthBucket\/OAuth2\/Exception\/ServerErrorException.html"," < LogicException",
                [        ]],["TemporarilyUnavailableException","AuthBucket\/OAuth2\/Exception\/TemporarilyUnavailableException.html"," < LogicException",
                [        ]],["UnauthorizedClientException","AuthBucket\/OAuth2\/Exception\/UnauthorizedClientException.html"," < LogicException",
                [        ]],["UnsupportedGrantTypeException","AuthBucket\/OAuth2\/Exception\/UnsupportedGrantTypeException.html"," < InvalidArgumentException",
                [        ]],["UnsupportedResponseTypeException","AuthBucket\/OAuth2\/Exception\/UnsupportedResponseTypeException.html"," < InvalidArgumentException",
                [        ]]        ]],["GrantType","AuthBucket\/OAuth2\/GrantType.html","",
                [["AbstractGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/AbstractGrantTypeHandler.html","",
                [        ]],["AuthorizationCodeGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/AuthorizationCodeGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["ClientCredentialsGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/ClientCredentialsGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["GrantTypeHandlerFactory","AuthBucket\/OAuth2\/GrantType\/GrantTypeHandlerFactory.html","",
                [        ]],["GrantTypeHandlerFactoryInterface","AuthBucket\/OAuth2\/GrantType\/GrantTypeHandlerFactoryInterface.html","",
                [        ]],["GrantTypeHandlerInterface","AuthBucket\/OAuth2\/GrantType\/GrantTypeHandlerInterface.html","",
                [        ]],["PasswordGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/PasswordGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["RefreshTokenGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/RefreshTokenGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]]        ]],["Model","AuthBucket\/OAuth2\/Model.html","",
                [["InMemory","AuthBucket\/OAuth2\/Model\/InMemory.html","",
                [["AbstractModelManager","AuthBucket\/OAuth2\/Model\/InMemory\/AbstractModelManager.html","",
                [        ]],["AccessToken","AuthBucket\/OAuth2\/Model\/InMemory\/AccessToken.html","",
                [        ]],["AccessTokenManager","AuthBucket\/OAuth2\/Model\/InMemory\/AccessTokenManager.html"," < AbstractModelManager",
                [        ]],["ModelManagerFactory","AuthBucket\/OAuth2\/Model\/InMemory\/ModelManagerFactory.html","",
                [        ]]        ]],["AccessTokenInterface","AuthBucket\/OAuth2\/Model\/AccessTokenInterface.html","",
                [        ]],["AccessTokenManagerInterface","AuthBucket\/OAuth2\/Model\/AccessTokenManagerInterface.html","",
                [        ]],["AuthorizeInterface","AuthBucket\/OAuth2\/Model\/AuthorizeInterface.html","",
                [        ]],["AuthorizeManagerInterface","AuthBucket\/OAuth2\/Model\/AuthorizeManagerInterface.html","",
                [        ]],["ClientInterface","AuthBucket\/OAuth2\/Model\/ClientInterface.html","",
                [        ]],["ClientManagerInterface","AuthBucket\/OAuth2\/Model\/ClientManagerInterface.html","",
                [        ]],["CodeInterface","AuthBucket\/OAuth2\/Model\/CodeInterface.html","",
                [        ]],["CodeManagerInterface","AuthBucket\/OAuth2\/Model\/CodeManagerInterface.html","",
                [        ]],["ModelInterface","AuthBucket\/OAuth2\/Model\/ModelInterface.html","",
                [        ]],["ModelManagerFactoryInterface","AuthBucket\/OAuth2\/Model\/ModelManagerFactoryInterface.html","",
                [        ]],["ModelManagerInterface","AuthBucket\/OAuth2\/Model\/ModelManagerInterface.html","",
                [        ]],["RefreshTokenInterface","AuthBucket\/OAuth2\/Model\/RefreshTokenInterface.html","",
                [        ]],["RefreshTokenManagerInterface","AuthBucket\/OAuth2\/Model\/RefreshTokenManagerInterface.html","",
                [        ]],["ScopeInterface","AuthBucket\/OAuth2\/Model\/ScopeInterface.html","",
                [        ]],["ScopeManagerInterface","AuthBucket\/OAuth2\/Model\/ScopeManagerInterface.html","",
                [        ]]        ]],["Provider","AuthBucket\/OAuth2\/Provider.html","",
                [["AuthBucketOAuth2ServiceProvider","AuthBucket\/OAuth2\/Provider\/AuthBucketOAuth2ServiceProvider.html","",
                [        ]]        ]],["ResourceType","AuthBucket\/OAuth2\/ResourceType.html","",
                [["AbstractResourceTypeHandler","AuthBucket\/OAuth2\/ResourceType\/AbstractResourceTypeHandler.html","",
                [        ]],["DebugEndpointResourceTypeHandler","AuthBucket\/OAuth2\/ResourceType\/DebugEndpointResourceTypeHandler.html"," < AbstractResourceTypeHandler",
                [        ]],["ModelResourceTypeHandler","AuthBucket\/OAuth2\/ResourceType\/ModelResourceTypeHandler.html"," < AbstractResourceTypeHandler",
                [        ]],["ResourceTypeHandlerFactory","AuthBucket\/OAuth2\/ResourceType\/ResourceTypeHandlerFactory.html","",
                [        ]],["ResourceTypeHandlerFactoryInterface","AuthBucket\/OAuth2\/ResourceType\/ResourceTypeHandlerFactoryInterface.html","",
                [        ]],["ResourceTypeHandlerInterface","AuthBucket\/OAuth2\/ResourceType\/ResourceTypeHandlerInterface.html","",
                [        ]]        ]],["ResponseType","AuthBucket\/OAuth2\/ResponseType.html","",
                [["AbstractResponseTypeHandler","AuthBucket\/OAuth2\/ResponseType\/AbstractResponseTypeHandler.html","",
                [        ]],["CodeResponseTypeHandler","AuthBucket\/OAuth2\/ResponseType\/CodeResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]],["ResponseTypeHandlerFactory","AuthBucket\/OAuth2\/ResponseType\/ResponseTypeHandlerFactory.html","",
                [        ]],["ResponseTypeHandlerFactoryInterface","AuthBucket\/OAuth2\/ResponseType\/ResponseTypeHandlerFactoryInterface.html","",
                [        ]],["ResponseTypeHandlerInterface","AuthBucket\/OAuth2\/ResponseType\/ResponseTypeHandlerInterface.html","",
                [        ]],["TokenResponseTypeHandler","AuthBucket\/OAuth2\/ResponseType\/TokenResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]]        ]],["Security",,"",
                [["Authentication",,"",
                [["Provider","AuthBucket\/OAuth2\/Security\/Authentication\/Provider.html","",
                [["ResourceProvider","AuthBucket\/OAuth2\/Security\/Authentication\/Provider\/ResourceProvider.html","",
                [        ]],["TokenProvider","AuthBucket\/OAuth2\/Security\/Authentication\/Provider\/TokenProvider.html","",
                [        ]]        ]],["Token","AuthBucket\/OAuth2\/Security\/Authentication\/Token.html","",
                [["AccessTokenToken","AuthBucket\/OAuth2\/Security\/Authentication\/Token\/AccessTokenToken.html"," < AbstractToken",
                [        ]],["ClientToken","AuthBucket\/OAuth2\/Security\/Authentication\/Token\/ClientToken.html"," < AbstractToken",
                [        ]]        ]]        ]],["Firewall","AuthBucket\/OAuth2\/Security\/Firewall.html","",
                [["ResourceListener","AuthBucket\/OAuth2\/Security\/Firewall\/ResourceListener.html","",
                [        ]],["TokenListener","AuthBucket\/OAuth2\/Security\/Firewall\/TokenListener.html","",
                [        ]]        ]]        ]],["TokenType","AuthBucket\/OAuth2\/TokenType.html","",
                [["AbstractTokenTypeHandler","AuthBucket\/OAuth2\/TokenType\/AbstractTokenTypeHandler.html","",
                [        ]],["BearerTokenTypeHandler","AuthBucket\/OAuth2\/TokenType\/BearerTokenTypeHandler.html"," < AbstractTokenTypeHandler",
                [        ]],["MacTokenTypeHandler","AuthBucket\/OAuth2\/TokenType\/MacTokenTypeHandler.html"," < AbstractTokenTypeHandler",
                [        ]],["TokenTypeHandlerFactory","AuthBucket\/OAuth2\/TokenType\/TokenTypeHandlerFactory.html","",
                [        ]],["TokenTypeHandlerFactoryInterface","AuthBucket\/OAuth2\/TokenType\/TokenTypeHandlerFactoryInterface.html","",
                [        ]],["TokenTypeHandlerInterface","AuthBucket\/OAuth2\/TokenType\/TokenTypeHandlerInterface.html","",
                [        ]]        ]],["Validator",,"",
                [["Constraints","AuthBucket\/OAuth2\/Validator\/Constraints.html","",
                [["AccessToken","AuthBucket\/OAuth2\/Validator\/Constraints\/AccessToken.html"," < Regex",
                [        ]],["AccessTokenValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/AccessTokenValidator.html"," < RegexValidator",
                [        ]],["ClientId","AuthBucket\/OAuth2\/Validator\/Constraints\/ClientId.html"," < Regex",
                [        ]],["ClientIdValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/ClientIdValidator.html"," < RegexValidator",
                [        ]],["ClientSecret","AuthBucket\/OAuth2\/Validator\/Constraints\/ClientSecret.html"," < Regex",
                [        ]],["ClientSecretValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/ClientSecretValidator.html"," < RegexValidator",
                [        ]],["Code","AuthBucket\/OAuth2\/Validator\/Constraints\/Code.html"," < Regex",
                [        ]],["CodeValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/CodeValidator.html"," < RegexValidator",
                [        ]],["Error","AuthBucket\/OAuth2\/Validator\/Constraints\/Error.html"," < Regex",
                [        ]],["ErrorDescription","AuthBucket\/OAuth2\/Validator\/Constraints\/ErrorDescription.html"," < Regex",
                [        ]],["ErrorDescriptionValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/ErrorDescriptionValidator.html"," < RegexValidator",
                [        ]],["ErrorUri","AuthBucket\/OAuth2\/Validator\/Constraints\/ErrorUri.html"," < Url",
                [        ]],["ErrorUriValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/ErrorUriValidator.html"," < UrlValidator",
                [        ]],["ErrorValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/ErrorValidator.html"," < RegexValidator",
                [        ]],["ExpiresIn","AuthBucket\/OAuth2\/Validator\/Constraints\/ExpiresIn.html"," < Regex",
                [        ]],["ExpiresInValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/ExpiresInValidator.html"," < RegexValidator",
                [        ]],["GrantType","AuthBucket\/OAuth2\/Validator\/Constraints\/GrantType.html"," < Regex",
                [        ]],["GrantTypeValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/GrantTypeValidator.html"," < RegexValidator",
                [        ]],["Password","AuthBucket\/OAuth2\/Validator\/Constraints\/Password.html"," < Regex",
                [        ]],["PasswordValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/PasswordValidator.html"," < RegexValidator",
                [        ]],["RedirectUri","AuthBucket\/OAuth2\/Validator\/Constraints\/RedirectUri.html"," < Url",
                [        ]],["RedirectUriValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/RedirectUriValidator.html"," < UrlValidator",
                [        ]],["RefreshToken","AuthBucket\/OAuth2\/Validator\/Constraints\/RefreshToken.html"," < Regex",
                [        ]],["RefreshTokenValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/RefreshTokenValidator.html"," < RegexValidator",
                [        ]],["ResponseType","AuthBucket\/OAuth2\/Validator\/Constraints\/ResponseType.html"," < Regex",
                [        ]],["ResponseTypeValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/ResponseTypeValidator.html"," < RegexValidator",
                [        ]],["Scope","AuthBucket\/OAuth2\/Validator\/Constraints\/Scope.html"," < Regex",
                [        ]],["ScopeValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/ScopeValidator.html"," < RegexValidator",
                [        ]],["State","AuthBucket\/OAuth2\/Validator\/Constraints\/State.html"," < Regex",
                [        ]],["StateValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/StateValidator.html"," < RegexValidator",
                [        ]],["TokenType","AuthBucket\/OAuth2\/Validator\/Constraints\/TokenType.html"," < Regex",
                [        ]],["TokenTypeValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/TokenTypeValidator.html"," < RegexValidator",
                [        ]],["Username","AuthBucket\/OAuth2\/Validator\/Constraints\/Username.html"," < Regex",
                [        ]],["UsernameValidator","AuthBucket\/OAuth2\/Validator\/Constraints\/UsernameValidator.html"," < RegexValidator",
                [        ]]        ]]        ]]        ]]        ]],["Pantarei",,"",
                [["Oauth2",,"",
                [["Controller","Pantarei\/Oauth2\/Controller.html","",
                [["AuthorizeController","Pantarei\/Oauth2\/Controller\/AuthorizeController.html","",
                [        ]],["TokenController","Pantarei\/Oauth2\/Controller\/TokenController.html","",
                [        ]]        ]],["Exception","Pantarei\/Oauth2\/Exception.html","",
                [["AccessDeniedException","Pantarei\/Oauth2\/Exception\/AccessDeniedException.html"," < LogicException",
                [        ]],["ExceptionInterface","Pantarei\/Oauth2\/Exception\/ExceptionInterface.html","",
                [        ]],["InvalidClientException","Pantarei\/Oauth2\/Exception\/InvalidClientException.html"," < InvalidArgumentException",
                [        ]],["InvalidGrantException","Pantarei\/Oauth2\/Exception\/InvalidGrantException.html"," < InvalidArgumentException",
                [        ]],["InvalidRequestException","Pantarei\/Oauth2\/Exception\/InvalidRequestException.html"," < InvalidArgumentException",
                [        ]],["InvalidScopeException","Pantarei\/Oauth2\/Exception\/InvalidScopeException.html"," < InvalidArgumentException",
                [        ]],["ServerErrorException","Pantarei\/Oauth2\/Exception\/ServerErrorException.html"," < LogicException",
                [        ]],["TemporarilyUnavailableException","Pantarei\/Oauth2\/Exception\/TemporarilyUnavailableException.html"," < LogicException",
                [        ]],["UnauthorizedClientException","Pantarei\/Oauth2\/Exception\/UnauthorizedClientException.html"," < LogicException",
                [        ]],["UnsupportedGrantTypeException","Pantarei\/Oauth2\/Exception\/UnsupportedGrantTypeException.html"," < InvalidArgumentException",
                [        ]],["UnsupportedResponseTypeException","Pantarei\/Oauth2\/Exception\/UnsupportedResponseTypeException.html"," < InvalidArgumentException",
                [        ]]        ]],["GrantType","Pantarei\/Oauth2\/GrantType.html","",
                [["AbstractGrantTypeHandler","Pantarei\/Oauth2\/GrantType\/AbstractGrantTypeHandler.html","",
                [        ]],["AuthorizationCodeGrantTypeHandler","Pantarei\/Oauth2\/GrantType\/AuthorizationCodeGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["ClientCredentialsGrantTypeHandler","Pantarei\/Oauth2\/GrantType\/ClientCredentialsGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["GrantTypeHandlerFactory","Pantarei\/Oauth2\/GrantType\/GrantTypeHandlerFactory.html","",
                [        ]],["GrantTypeHandlerFactoryInterface","Pantarei\/Oauth2\/GrantType\/GrantTypeHandlerFactoryInterface.html","",
                [        ]],["GrantTypeHandlerInterface","Pantarei\/Oauth2\/GrantType\/GrantTypeHandlerInterface.html","",
                [        ]],["PasswordGrantTypeHandler","Pantarei\/Oauth2\/GrantType\/PasswordGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["RefreshTokenGrantTypeHandler","Pantarei\/Oauth2\/GrantType\/RefreshTokenGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]]        ]],["Model","Pantarei\/Oauth2\/Model.html","",
                [["AccessTokenInterface","Pantarei\/Oauth2\/Model\/AccessTokenInterface.html","",
                [        ]],["AccessTokenManagerInterface","Pantarei\/Oauth2\/Model\/AccessTokenManagerInterface.html","",
                [        ]],["AuthorizeInterface","Pantarei\/Oauth2\/Model\/AuthorizeInterface.html","",
                [        ]],["AuthorizeManagerInterface","Pantarei\/Oauth2\/Model\/AuthorizeManagerInterface.html","",
                [        ]],["ClientInterface","Pantarei\/Oauth2\/Model\/ClientInterface.html","",
                [        ]],["ClientManagerInterface","Pantarei\/Oauth2\/Model\/ClientManagerInterface.html","",
                [        ]],["CodeInterface","Pantarei\/Oauth2\/Model\/CodeInterface.html","",
                [        ]],["CodeManagerInterface","Pantarei\/Oauth2\/Model\/CodeManagerInterface.html","",
                [        ]],["ModelInterface","Pantarei\/Oauth2\/Model\/ModelInterface.html","",
                [        ]],["ModelManagerFactoryInterface","Pantarei\/Oauth2\/Model\/ModelManagerFactoryInterface.html","",
                [        ]],["ModelManagerInterface","Pantarei\/Oauth2\/Model\/ModelManagerInterface.html","",
                [        ]],["RefreshTokenInterface","Pantarei\/Oauth2\/Model\/RefreshTokenInterface.html","",
                [        ]],["RefreshTokenManagerInterface","Pantarei\/Oauth2\/Model\/RefreshTokenManagerInterface.html","",
                [        ]],["ScopeInterface","Pantarei\/Oauth2\/Model\/ScopeInterface.html","",
                [        ]],["ScopeManagerInterface","Pantarei\/Oauth2\/Model\/ScopeManagerInterface.html","",
                [        ]]        ]],["Provider","Pantarei\/Oauth2\/Provider.html","",
                [["Oauth2ServiceProvider","Pantarei\/Oauth2\/Provider\/Oauth2ServiceProvider.html","",
                [        ]]        ]],["ResponseType","Pantarei\/Oauth2\/ResponseType.html","",
                [["AbstractResponseTypeHandler","Pantarei\/Oauth2\/ResponseType\/AbstractResponseTypeHandler.html","",
                [        ]],["CodeResponseTypeHandler","Pantarei\/Oauth2\/ResponseType\/CodeResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]],["ResponseTypeHandlerFactory","Pantarei\/Oauth2\/ResponseType\/ResponseTypeHandlerFactory.html","",
                [        ]],["ResponseTypeHandlerFactoryInterface","Pantarei\/Oauth2\/ResponseType\/ResponseTypeHandlerFactoryInterface.html","",
                [        ]],["ResponseTypeHandlerInterface","Pantarei\/Oauth2\/ResponseType\/ResponseTypeHandlerInterface.html","",
                [        ]],["TokenResponseTypeHandler","Pantarei\/Oauth2\/ResponseType\/TokenResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]]        ]],["Security",,"",
                [["Authentication",,"",
                [["Provider","Pantarei\/Oauth2\/Security\/Authentication\/Provider.html","",
                [["ResourceProvider","Pantarei\/Oauth2\/Security\/Authentication\/Provider\/ResourceProvider.html","",
                [        ]],["TokenProvider","Pantarei\/Oauth2\/Security\/Authentication\/Provider\/TokenProvider.html","",
                [        ]]        ]],["Token","Pantarei\/Oauth2\/Security\/Authentication\/Token.html","",
                [["AccessToken","Pantarei\/Oauth2\/Security\/Authentication\/Token\/AccessToken.html"," < AbstractToken",
                [        ]],["ClientToken","Pantarei\/Oauth2\/Security\/Authentication\/Token\/ClientToken.html"," < AbstractToken",
                [        ]]        ]]        ]],["Firewall","Pantarei\/Oauth2\/Security\/Firewall.html","",
                [["ResourceListener","Pantarei\/Oauth2\/Security\/Firewall\/ResourceListener.html","",
                [        ]],["TokenListener","Pantarei\/Oauth2\/Security\/Firewall\/TokenListener.html","",
                [        ]]        ]]        ]],["TokenType","Pantarei\/Oauth2\/TokenType.html","",
                [["BearerTokenTypeHandler","Pantarei\/Oauth2\/TokenType\/BearerTokenTypeHandler.html","",
                [        ]],["MacTokenTypeHandler","Pantarei\/Oauth2\/TokenType\/MacTokenTypeHandler.html","",
                [        ]],["TokenTypeHandlerFactory","Pantarei\/Oauth2\/TokenType\/TokenTypeHandlerFactory.html","",
                [        ]],["TokenTypeHandlerFactoryInterface","Pantarei\/Oauth2\/TokenType\/TokenTypeHandlerFactoryInterface.html","",
                [        ]],["TokenTypeHandlerInterface","Pantarei\/Oauth2\/TokenType\/TokenTypeHandlerInterface.html","",
                [        ]]        ]],["Util","Pantarei\/Oauth2\/Util.html","",
                [["Filter","Pantarei\/Oauth2\/Util\/Filter.html","",
                [        ]],["JsonResponse","Pantarei\/Oauth2\/Util\/JsonResponse.html"," < JsonResponse",
                [        ]],["RedirectResponse","Pantarei\/Oauth2\/Util\/RedirectResponse.html"," < RedirectResponse",
                [        ]]        ]]        ]]        ]]        ]

