var tree = [["AuthBucket",,"",
                [["OAuth2",,"",
                [["Controller","AuthBucket\/OAuth2\/Controller.html","",
                [["AuthorizeController","AuthBucket\/OAuth2\/Controller\/AuthorizeController.html","",
                [        ]],["DebugController","AuthBucket\/OAuth2\/Controller\/DebugController.html","",
                [        ]],["TokenController","AuthBucket\/OAuth2\/Controller\/TokenController.html","",
                [        ]]        ]],["EventListener","AuthBucket\/OAuth2\/EventListener.html","",
                [["ExceptionListener","AuthBucket\/OAuth2\/EventListener\/ExceptionListener.html","",
                [        ]]        ]],["Exception","AuthBucket\/OAuth2\/Exception.html","",
                [["AccessDeniedException","AuthBucket\/OAuth2\/Exception\/AccessDeniedException.html"," < LogicException",
                [        ]],["ExceptionInterface","AuthBucket\/OAuth2\/Exception\/ExceptionInterface.html","",
                [        ]],["InvalidClientException","AuthBucket\/OAuth2\/Exception\/InvalidClientException.html"," < InvalidArgumentException",
                [        ]],["InvalidGrantException","AuthBucket\/OAuth2\/Exception\/InvalidGrantException.html"," < InvalidArgumentException",
                [        ]],["InvalidRequestException","AuthBucket\/OAuth2\/Exception\/InvalidRequestException.html"," < InvalidArgumentException",
                [        ]],["InvalidScopeException","AuthBucket\/OAuth2\/Exception\/InvalidScopeException.html"," < InvalidArgumentException",
                [        ]],["ServerErrorException","AuthBucket\/OAuth2\/Exception\/ServerErrorException.html"," < LogicException",
                [        ]],["TemporarilyUnavailableException","AuthBucket\/OAuth2\/Exception\/TemporarilyUnavailableException.html"," < LogicException",
                [        ]],["UnauthorizedClientException","AuthBucket\/OAuth2\/Exception\/UnauthorizedClientException.html"," < LogicException",
                [        ]],["UnsupportedGrantTypeException","AuthBucket\/OAuth2\/Exception\/UnsupportedGrantTypeException.html"," < InvalidArgumentException",
                [        ]],["UnsupportedResponseTypeException","AuthBucket\/OAuth2\/Exception\/UnsupportedResponseTypeException.html"," < InvalidArgumentException",
                [        ]]        ]],["GrantType","AuthBucket\/OAuth2\/GrantType.html","",
                [["AbstractGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/AbstractGrantTypeHandler.html","",
                [        ]],["AuthorizationCodeGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/AuthorizationCodeGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["ClientCredentialsGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/ClientCredentialsGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["GrantTypeHandlerFactory","AuthBucket\/OAuth2\/GrantType\/GrantTypeHandlerFactory.html","",
                [        ]],["GrantTypeHandlerFactoryInterface","AuthBucket\/OAuth2\/GrantType\/GrantTypeHandlerFactoryInterface.html","",
                [        ]],["GrantTypeHandlerInterface","AuthBucket\/OAuth2\/GrantType\/GrantTypeHandlerInterface.html","",
                [        ]],["PasswordGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/PasswordGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["RefreshTokenGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/RefreshTokenGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]]        ]],["Model","AuthBucket\/OAuth2\/Model.html","",
                [["AccessTokenInterface","AuthBucket\/OAuth2\/Model\/AccessTokenInterface.html","",
                [        ]],["AccessTokenManagerInterface","AuthBucket\/OAuth2\/Model\/AccessTokenManagerInterface.html","",
                [        ]],["AuthorizeInterface","AuthBucket\/OAuth2\/Model\/AuthorizeInterface.html","",
                [        ]],["AuthorizeManagerInterface","AuthBucket\/OAuth2\/Model\/AuthorizeManagerInterface.html","",
                [        ]],["ClientInterface","AuthBucket\/OAuth2\/Model\/ClientInterface.html","",
                [        ]],["ClientManagerInterface","AuthBucket\/OAuth2\/Model\/ClientManagerInterface.html","",
                [        ]],["CodeInterface","AuthBucket\/OAuth2\/Model\/CodeInterface.html","",
                [        ]],["CodeManagerInterface","AuthBucket\/OAuth2\/Model\/CodeManagerInterface.html","",
                [        ]],["ModelInterface","AuthBucket\/OAuth2\/Model\/ModelInterface.html","",
                [        ]],["ModelManagerFactoryInterface","AuthBucket\/OAuth2\/Model\/ModelManagerFactoryInterface.html","",
                [        ]],["ModelManagerInterface","AuthBucket\/OAuth2\/Model\/ModelManagerInterface.html","",
                [        ]],["RefreshTokenInterface","AuthBucket\/OAuth2\/Model\/RefreshTokenInterface.html","",
                [        ]],["RefreshTokenManagerInterface","AuthBucket\/OAuth2\/Model\/RefreshTokenManagerInterface.html","",
                [        ]],["ScopeInterface","AuthBucket\/OAuth2\/Model\/ScopeInterface.html","",
                [        ]],["ScopeManagerInterface","AuthBucket\/OAuth2\/Model\/ScopeManagerInterface.html","",
                [        ]]        ]],["Provider","AuthBucket\/OAuth2\/Provider.html","",
                [["OAuth2ServiceProvider","AuthBucket\/OAuth2\/Provider\/OAuth2ServiceProvider.html","",
                [        ]]        ]],["ResponseType","AuthBucket\/OAuth2\/ResponseType.html","",
                [["AbstractResponseTypeHandler","AuthBucket\/OAuth2\/ResponseType\/AbstractResponseTypeHandler.html","",
                [        ]],["CodeResponseTypeHandler","AuthBucket\/OAuth2\/ResponseType\/CodeResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]],["ResponseTypeHandlerFactory","AuthBucket\/OAuth2\/ResponseType\/ResponseTypeHandlerFactory.html","",
                [        ]],["ResponseTypeHandlerFactoryInterface","AuthBucket\/OAuth2\/ResponseType\/ResponseTypeHandlerFactoryInterface.html","",
                [        ]],["ResponseTypeHandlerInterface","AuthBucket\/OAuth2\/ResponseType\/ResponseTypeHandlerInterface.html","",
                [        ]],["TokenResponseTypeHandler","AuthBucket\/OAuth2\/ResponseType\/TokenResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]]        ]],["Security",,"",
                [["Authentication",,"",
                [["Provider","AuthBucket\/OAuth2\/Security\/Authentication\/Provider.html","",
                [["ResourceProvider","AuthBucket\/OAuth2\/Security\/Authentication\/Provider\/ResourceProvider.html","",
                [        ]],["TokenProvider","AuthBucket\/OAuth2\/Security\/Authentication\/Provider\/TokenProvider.html","",
                [        ]]        ]],["Token","AuthBucket\/OAuth2\/Security\/Authentication\/Token.html","",
                [["AccessToken","AuthBucket\/OAuth2\/Security\/Authentication\/Token\/AccessToken.html"," < AbstractToken",
                [        ]],["ClientToken","AuthBucket\/OAuth2\/Security\/Authentication\/Token\/ClientToken.html"," < AbstractToken",
                [        ]]        ]]        ]],["Firewall","AuthBucket\/OAuth2\/Security\/Firewall.html","",
                [["ResourceListener","AuthBucket\/OAuth2\/Security\/Firewall\/ResourceListener.html","",
                [        ]],["TokenListener","AuthBucket\/OAuth2\/Security\/Firewall\/TokenListener.html","",
                [        ]]        ]]        ]],["Tests","AuthBucket\/OAuth2\/Tests.html","",
                [["Controller","AuthBucket\/OAuth2\/Tests\/Controller.html","",
                [["AuthorizateControllerTest","AuthBucket\/OAuth2\/Tests\/Controller\/AuthorizateControllerTest.html"," < WebTestCase",
                [        ]],["DebugControllerTest","AuthBucket\/OAuth2\/Tests\/Controller\/DebugControllerTest.html"," < WebTestCase",
                [        ]],["TokenControllerTest","AuthBucket\/OAuth2\/Tests\/Controller\/TokenControllerTest.html"," < WebTestCase",
                [        ]]        ]],["DataFixtures",,"",
                [["ORM","AuthBucket\/OAuth2\/Tests\/DataFixtures\/ORM.html","",
                [["AccessTokenFixture","AuthBucket\/OAuth2\/Tests\/DataFixtures\/ORM\/AccessTokenFixture.html","",
                [        ]],["AuthorizeFixture","AuthBucket\/OAuth2\/Tests\/DataFixtures\/ORM\/AuthorizeFixture.html","",
                [        ]],["ClientFixture","AuthBucket\/OAuth2\/Tests\/DataFixtures\/ORM\/ClientFixture.html","",
                [        ]],["CodeFixture","AuthBucket\/OAuth2\/Tests\/DataFixtures\/ORM\/CodeFixture.html","",
                [        ]],["RefreshTokenFixture","AuthBucket\/OAuth2\/Tests\/DataFixtures\/ORM\/RefreshTokenFixture.html","",
                [        ]],["ScopeFixture","AuthBucket\/OAuth2\/Tests\/DataFixtures\/ORM\/ScopeFixture.html","",
                [        ]]        ]]        ]],["Entity","AuthBucket\/OAuth2\/Tests\/Entity.html","",
                [["AccessToken","AuthBucket\/OAuth2\/Tests\/Entity\/AccessToken.html","",
                [        ]],["AccessTokenRepository","AuthBucket\/OAuth2\/Tests\/Entity\/AccessTokenRepository.html"," < EntityRepository",
                [        ]],["Authorize","AuthBucket\/OAuth2\/Tests\/Entity\/Authorize.html","",
                [        ]],["AuthorizeRepository","AuthBucket\/OAuth2\/Tests\/Entity\/AuthorizeRepository.html"," < EntityRepository",
                [        ]],["Client","AuthBucket\/OAuth2\/Tests\/Entity\/Client.html","",
                [        ]],["ClientRepository","AuthBucket\/OAuth2\/Tests\/Entity\/ClientRepository.html"," < EntityRepository",
                [        ]],["Code","AuthBucket\/OAuth2\/Tests\/Entity\/Code.html","",
                [        ]],["CodeRepository","AuthBucket\/OAuth2\/Tests\/Entity\/CodeRepository.html"," < EntityRepository",
                [        ]],["ModelManagerFactory","AuthBucket\/OAuth2\/Tests\/Entity\/ModelManagerFactory.html","",
                [        ]],["RefreshToken","AuthBucket\/OAuth2\/Tests\/Entity\/RefreshToken.html","",
                [        ]],["RefreshTokenRepository","AuthBucket\/OAuth2\/Tests\/Entity\/RefreshTokenRepository.html"," < EntityRepository",
                [        ]],["Scope","AuthBucket\/OAuth2\/Tests\/Entity\/Scope.html","",
                [        ]],["ScopeRepository","AuthBucket\/OAuth2\/Tests\/Entity\/ScopeRepository.html"," < EntityRepository",
                [        ]]        ]],["Exception","AuthBucket\/OAuth2\/Tests\/Exception.html","",
                [["AccessDeniedExceptionTest","AuthBucket\/OAuth2\/Tests\/Exception\/AccessDeniedExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["InvalidClientExceptionTest","AuthBucket\/OAuth2\/Tests\/Exception\/InvalidClientExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["InvalidGrantExceptionTest","AuthBucket\/OAuth2\/Tests\/Exception\/InvalidGrantExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["InvalidRequestExceptionTest","AuthBucket\/OAuth2\/Tests\/Exception\/InvalidRequestExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["InvalidScopeExceptionTest","AuthBucket\/OAuth2\/Tests\/Exception\/InvalidScopeExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["ServerErrorExceptionTest","AuthBucket\/OAuth2\/Tests\/Exception\/ServerErrorExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["TemporarilyUnavailableExceptionTest","AuthBucket\/OAuth2\/Tests\/Exception\/TemporarilyUnavailableExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["UnauthorizedClientExceptionTest","AuthBucket\/OAuth2\/Tests\/Exception\/UnauthorizedClientExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["UnsupportedGrantTypeExceptionTest","AuthBucket\/OAuth2\/Tests\/Exception\/UnsupportedGrantTypeExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["UnsupportedResponseTypeTest","AuthBucket\/OAuth2\/Tests\/Exception\/UnsupportedResponseTypeTest.html"," < PHPUnit_Framework_TestCase",
                [        ]]        ]],["GrantType","AuthBucket\/OAuth2\/Tests\/GrantType.html","",
                [["AuthorizationCodeGrantTypeHandlerTest","AuthBucket\/OAuth2\/Tests\/GrantType\/AuthorizationCodeGrantTypeHandlerTest.html"," < WebTestCase",
                [        ]],["BarGrantTypeHandler","AuthBucket\/OAuth2\/Tests\/GrantType\/BarGrantTypeHandler.html","",
                [        ]],["ClientCredentialsGrantTypeHandlerTest","AuthBucket\/OAuth2\/Tests\/GrantType\/ClientCredentialsGrantTypeHandlerTest.html"," < WebTestCase",
                [        ]],["FooGrantTypeHandler","AuthBucket\/OAuth2\/Tests\/GrantType\/FooGrantTypeHandler.html","",
                [        ]],["GrantTypeHandlerFactoryTest","AuthBucket\/OAuth2\/Tests\/GrantType\/GrantTypeHandlerFactoryTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["PasswordGrantTypeHandlerTest","AuthBucket\/OAuth2\/Tests\/GrantType\/PasswordGrantTypeHandlerTest.html"," < WebTestCase",
                [        ]],["RefreshTokenGrantTypeHandlerTest","AuthBucket\/OAuth2\/Tests\/GrantType\/RefreshTokenGrantTypeHandlerTest.html"," < WebTestCase",
                [        ]]        ]],["ResponseType","AuthBucket\/OAuth2\/Tests\/ResponseType.html","",
                [["BarResponseTypeHandler","AuthBucket\/OAuth2\/Tests\/ResponseType\/BarResponseTypeHandler.html","",
                [        ]],["CodeResponseTypeHandlerTest","AuthBucket\/OAuth2\/Tests\/ResponseType\/CodeResponseTypeHandlerTest.html"," < WebTestCase",
                [        ]],["FooResponseTypeHandler","AuthBucket\/OAuth2\/Tests\/ResponseType\/FooResponseTypeHandler.html","",
                [        ]],["ResponseTypeHandlerFactoryTest","AuthBucket\/OAuth2\/Tests\/ResponseType\/ResponseTypeHandlerFactoryTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["TokenResponseTypeHandlerTest","AuthBucket\/OAuth2\/Tests\/ResponseType\/TokenResponseTypeHandlerTest.html"," < WebTestCase",
                [        ]]        ]],["TokenType","AuthBucket\/OAuth2\/Tests\/TokenType.html","",
                [["BarModelManagerFactory","AuthBucket\/OAuth2\/Tests\/TokenType\/BarModelManagerFactory.html","",
                [        ]],["BarTokenTypeHandler","AuthBucket\/OAuth2\/Tests\/TokenType\/BarTokenTypeHandler.html","",
                [        ]],["BearerTokenTypeHandlerTest","AuthBucket\/OAuth2\/Tests\/TokenType\/BearerTokenTypeHandlerTest.html"," < WebTestCase",
                [        ]],["FooModelManagerFactory","AuthBucket\/OAuth2\/Tests\/TokenType\/FooModelManagerFactory.html","",
                [        ]],["FooTokenTypeHandler","AuthBucket\/OAuth2\/Tests\/TokenType\/FooTokenTypeHandler.html","",
                [        ]],["MacTokenTypeHandlerTest","AuthBucket\/OAuth2\/Tests\/TokenType\/MacTokenTypeHandlerTest.html"," < WebTestCase",
                [        ]],["TokenTypeHandlerFactoryTest","AuthBucket\/OAuth2\/Tests\/TokenType\/TokenTypeHandlerFactoryTest.html"," < PHPUnit_Framework_TestCase",
                [        ]]        ]],["AutoloadTest","AuthBucket\/OAuth2\/Tests\/AutoloadTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["OAuth2Test","AuthBucket\/OAuth2\/Tests\/OAuth2Test.html"," < WebTestCase",
                [        ]],["WebTestCase","AuthBucket\/OAuth2\/Tests\/WebTestCase.html"," < WebTestCase",
                [        ]],["WebTestCaseNullModelManagerTest","AuthBucket\/OAuth2\/Tests\/WebTestCaseNullModelManagerTest.html"," < WebTestCase",
                [        ]],["WebTestCaseNullUserProviderTest","AuthBucket\/OAuth2\/Tests\/WebTestCaseNullUserProviderTest.html"," < WebTestCase",
                [        ]],["WebTestCaseTest","AuthBucket\/OAuth2\/Tests\/WebTestCaseTest.html"," < WebTestCase",
                [        ]]        ]],["TokenType","AuthBucket\/OAuth2\/TokenType.html","",
                [["BearerTokenTypeHandler","AuthBucket\/OAuth2\/TokenType\/BearerTokenTypeHandler.html","",
                [        ]],["MacTokenTypeHandler","AuthBucket\/OAuth2\/TokenType\/MacTokenTypeHandler.html","",
                [        ]],["TokenTypeHandlerFactory","AuthBucket\/OAuth2\/TokenType\/TokenTypeHandlerFactory.html","",
                [        ]],["TokenTypeHandlerFactoryInterface","AuthBucket\/OAuth2\/TokenType\/TokenTypeHandlerFactoryInterface.html","",
                [        ]],["TokenTypeHandlerInterface","AuthBucket\/OAuth2\/TokenType\/TokenTypeHandlerInterface.html","",
                [        ]]        ]],["Util","AuthBucket\/OAuth2\/Util.html","",
                [["Filter","AuthBucket\/OAuth2\/Util\/Filter.html","",
                [        ]],["JsonResponse","AuthBucket\/OAuth2\/Util\/JsonResponse.html"," < JsonResponse",
                [        ]],["RedirectResponse","AuthBucket\/OAuth2\/Util\/RedirectResponse.html"," < RedirectResponse",
                [        ]]        ]]        ]]        ]]        ]

