var tree = [["AuthBucket",,"",
                [["OAuth2",,"",
                [["GrantType","AuthBucket\/OAuth2\/GrantType.html","",
                [["AuthorizationCodeGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/AuthorizationCodeGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["ClientCredentialsGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/ClientCredentialsGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["GrantTypeHandlerFactory","AuthBucket\/OAuth2\/GrantType\/GrantTypeHandlerFactory.html","",
                [        ]],["PasswordGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/PasswordGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["RefreshTokenGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/RefreshTokenGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]]        ]],["ResourceType","AuthBucket\/OAuth2\/ResourceType.html","",
                [["DebugEndpointResourceTypeHandler","AuthBucket\/OAuth2\/ResourceType\/DebugEndpointResourceTypeHandler.html"," < AbstractResourceTypeHandler",
                [        ]],["ModelResourceTypeHandler","AuthBucket\/OAuth2\/ResourceType\/ModelResourceTypeHandler.html"," < AbstractResourceTypeHandler",
                [        ]],["ResourceTypeHandlerFactory","AuthBucket\/OAuth2\/ResourceType\/ResourceTypeHandlerFactory.html","",
                [        ]]        ]],["ResponseType","AuthBucket\/OAuth2\/ResponseType.html","",
                [["CodeResponseTypeHandler","AuthBucket\/OAuth2\/ResponseType\/CodeResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]],["ResponseTypeHandlerFactory","AuthBucket\/OAuth2\/ResponseType\/ResponseTypeHandlerFactory.html","",
                [        ]],["TokenResponseTypeHandler","AuthBucket\/OAuth2\/ResponseType\/TokenResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]]        ]],["TokenType","AuthBucket\/OAuth2\/TokenType.html","",
                [["AbstractTokenTypeHandler","AuthBucket\/OAuth2\/TokenType\/AbstractTokenTypeHandler.html","",
                [        ]],["BearerTokenTypeHandler","AuthBucket\/OAuth2\/TokenType\/BearerTokenTypeHandler.html"," < AbstractTokenTypeHandler",
                [        ]],["TokenTypeHandlerFactory","AuthBucket\/OAuth2\/TokenType\/TokenTypeHandlerFactory.html","",
                [        ]]        ]]        ]]        ]]        ]

