<?php

/**
 * This file is part of the pantarei/oauth2 package.
 *
 * (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Pantarei\OAuth2\Tests\Entity;

use Doctrine\ORM\EntityRepository;
use Pantarei\OAuth2\Model\AuthorizeInterface;
use Pantarei\OAuth2\Model\AuthorizeManagerInterface;

/**
 * AuthorizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorizeRepository extends EntityRepository implements AuthorizeManagerInterface
{
    public function createAuthorize()
    {
        return new $this->getClassName();
    }

    public function deleteAuthorize(AuthorizeInterface $authorize)
    {
        $this->remove($authorize);
        $this->flush();
    }

    public function findAuthorizeByClientIdUsername($client_id, $username)
    {
        return $this->findOneBy(array(
            'client_id' => $client_id,
            'username' => $username,
        ));
    }

    public function reloadAuthorize(AuthorizeInterface $authorize)
    {
        $this->refresh($authorize);
    }

    public function updateAuthorize(AuthorizeInterface $authorize)
    {
        $this->persist($authorize);
        $this->flush();
    }
}
