<?php

/**
 * This file is part of the pantarei/oauth2 package.
 *
 * (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Pantarei\OAuth2\Tests\Entity;

use Doctrine\ORM\EntityRepository;
use Pantarei\OAuth2\Model\ClientInterface;
use Pantarei\OAuth2\Model\ClientManagerInterface;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository implements ClientManagerInterface
{
    public function createClient()
    {
        return new $this->getClassName();
    }

    public function deleteClient(ClientInterface $client)
    {
        $this->remove($client);
        $this->flush();
    }

    public function findClientByClientId($client_id)
    {
        return $this->findOneBy(array(
            'client_id' => $client_id,
        ));
    }

    public function reloadClient(ClientInterface $client)
    {
        $this->refresh($client);
    }

    public function updateClient(ClientInterface $client)
    {
        $this->persist($client);
        $this->flush();
    }
}
