<?php

/**
 * This file is part of the pantarei/oauth2 package.
 *
 * (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Pantarei\OAuth2\Tests\Entity;

use Doctrine\ORM\EntityRepository;
use Pantarei\OAuth2\Model\RefreshTokensManagerInterface;

/**
 * RefreshTokensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefreshTokensRepository extends EntityRepository implements RefreshTokensManagerInterface
{
    public function loadByRefreshToken($refresh_token)
    {
        $result = $this->findOneBy(array(
            'refresh_token' => $refresh_token,
        ));
        if ($result !== null) {
            return $result;
        }

        return false;
    }
}
