<?php

/**
 * This file is part of the pantarei/oauth2 package.
 *
 * (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Pantarei\OAuth2\Tests\Entity;

use Doctrine\ORM\EntityRepository;
use Pantarei\OAuth2\Model\ScopeInterface;
use Pantarei\OAuth2\Model\ScopeManagerInterface;

/**
 * ScopeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScopeRepository extends EntityRepository implements ScopeManagerInterface
{
    public function createScope()
    {
        return new $this->getClassName();
    }

    public function deleteScope(ScopeInterface $scope)
    {
        $this->remove($scope);
        $this->flush();
    }

    public function findScopes()
    {
        return $this->findAll();
    }

    public function reloadScope(ScopeInterface $scope)
    {
        $this->refresh($scope);
    }

    public function updateScope(ScopeInterface $scope)
    {
        $this->persist($scope);
        $this->flush();
    }
}
