<?php

/**
 * This file is part of the pantarei/oauth2 package.
 *
 * (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Pantarei\OAuth2\Tests\Model;

use Pantarei\OAuth2\Model\AccessTokenManagerInterface;

/**
 * AccessTokenManager
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessTokenManager extends AbstractModelManager implements AccessTokenManagerInterface
{
    public function findAccessTokenByAccessToken($access_token)
    {
        return $this->findOneBy(array(
            'access_token' => $access_token,
        ));
    }
}
