<?php

/**
 * This file is part of the pantarei/oauth2 package.
 *
 * (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Pantarei\OAuth2\Tests\Model;

use Pantarei\OAuth2\Model\ScopeManagerInterface;

/**
 * ScopeManager
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScopeManager extends AbstractModelManager implements ScopeManagerInterface
{
    public function findScopes()
    {
        return $this->findAll();
    }
}
