var tree = [["AuthBucket",,"",
                [["OAuth2",,"",
                [["Controller","AuthBucket\/OAuth2\/Controller.html","",
                [["AuthorizeController","AuthBucket\/OAuth2\/Controller\/AuthorizeController.html","",
                [        ]],["ResourceController","AuthBucket\/OAuth2\/Controller\/ResourceController.html","",
                [        ]],["TokenController","AuthBucket\/OAuth2\/Controller\/TokenController.html","",
                [        ]]        ]],["EventListener","AuthBucket\/OAuth2\/EventListener.html","",
                [["ExceptionListener","AuthBucket\/OAuth2\/EventListener\/ExceptionListener.html","",
                [        ]]        ]],["Exception","AuthBucket\/OAuth2\/Exception.html","",
                [["AccessDeniedException","AuthBucket\/OAuth2\/Exception\/AccessDeniedException.html"," < LogicException",
                [        ]],["ExceptionInterface","AuthBucket\/OAuth2\/Exception\/ExceptionInterface.html","",
                [        ]],["InvalidClientException","AuthBucket\/OAuth2\/Exception\/InvalidClientException.html"," < InvalidArgumentException",
                [        ]],["InvalidGrantException","AuthBucket\/OAuth2\/Exception\/InvalidGrantException.html"," < InvalidArgumentException",
                [        ]],["InvalidRequestException","AuthBucket\/OAuth2\/Exception\/InvalidRequestException.html"," < InvalidArgumentException",
                [        ]],["InvalidScopeException","AuthBucket\/OAuth2\/Exception\/InvalidScopeException.html"," < InvalidArgumentException",
                [        ]],["ServerErrorException","AuthBucket\/OAuth2\/Exception\/ServerErrorException.html"," < LogicException",
                [        ]],["TemporarilyUnavailableException","AuthBucket\/OAuth2\/Exception\/TemporarilyUnavailableException.html"," < LogicException",
                [        ]],["UnauthorizedClientException","AuthBucket\/OAuth2\/Exception\/UnauthorizedClientException.html"," < LogicException",
                [        ]],["UnsupportedGrantTypeException","AuthBucket\/OAuth2\/Exception\/UnsupportedGrantTypeException.html"," < InvalidArgumentException",
                [        ]],["UnsupportedResponseTypeException","AuthBucket\/OAuth2\/Exception\/UnsupportedResponseTypeException.html"," < InvalidArgumentException",
                [        ]]        ]],["GrantType","AuthBucket\/OAuth2\/GrantType.html","",
                [["AbstractGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/AbstractGrantTypeHandler.html","",
                [        ]],["AuthorizationCodeGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/AuthorizationCodeGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["ClientCredentialsGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/ClientCredentialsGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["GrantTypeHandlerFactory","AuthBucket\/OAuth2\/GrantType\/GrantTypeHandlerFactory.html","",
                [        ]],["GrantTypeHandlerFactoryInterface","AuthBucket\/OAuth2\/GrantType\/GrantTypeHandlerFactoryInterface.html","",
                [        ]],["GrantTypeHandlerInterface","AuthBucket\/OAuth2\/GrantType\/GrantTypeHandlerInterface.html","",
                [        ]],["PasswordGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/PasswordGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["RefreshTokenGrantTypeHandler","AuthBucket\/OAuth2\/GrantType\/RefreshTokenGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]]        ]],["Model","AuthBucket\/OAuth2\/Model.html","",
                [["AccessTokenInterface","AuthBucket\/OAuth2\/Model\/AccessTokenInterface.html","",
                [        ]],["AccessTokenManagerInterface","AuthBucket\/OAuth2\/Model\/AccessTokenManagerInterface.html","",
                [        ]],["AuthorizeInterface","AuthBucket\/OAuth2\/Model\/AuthorizeInterface.html","",
                [        ]],["AuthorizeManagerInterface","AuthBucket\/OAuth2\/Model\/AuthorizeManagerInterface.html","",
                [        ]],["ClientInterface","AuthBucket\/OAuth2\/Model\/ClientInterface.html","",
                [        ]],["ClientManagerInterface","AuthBucket\/OAuth2\/Model\/ClientManagerInterface.html","",
                [        ]],["CodeInterface","AuthBucket\/OAuth2\/Model\/CodeInterface.html","",
                [        ]],["CodeManagerInterface","AuthBucket\/OAuth2\/Model\/CodeManagerInterface.html","",
                [        ]],["ModelInterface","AuthBucket\/OAuth2\/Model\/ModelInterface.html","",
                [        ]],["ModelManagerFactoryInterface","AuthBucket\/OAuth2\/Model\/ModelManagerFactoryInterface.html","",
                [        ]],["ModelManagerInterface","AuthBucket\/OAuth2\/Model\/ModelManagerInterface.html","",
                [        ]],["RefreshTokenInterface","AuthBucket\/OAuth2\/Model\/RefreshTokenInterface.html","",
                [        ]],["RefreshTokenManagerInterface","AuthBucket\/OAuth2\/Model\/RefreshTokenManagerInterface.html","",
                [        ]],["ScopeInterface","AuthBucket\/OAuth2\/Model\/ScopeInterface.html","",
                [        ]],["ScopeManagerInterface","AuthBucket\/OAuth2\/Model\/ScopeManagerInterface.html","",
                [        ]]        ]],["Provider","AuthBucket\/OAuth2\/Provider.html","",
                [["OAuth2ServiceProvider","AuthBucket\/OAuth2\/Provider\/OAuth2ServiceProvider.html","",
                [        ]]        ]],["ResponseType","AuthBucket\/OAuth2\/ResponseType.html","",
                [["AbstractResponseTypeHandler","AuthBucket\/OAuth2\/ResponseType\/AbstractResponseTypeHandler.html","",
                [        ]],["CodeResponseTypeHandler","AuthBucket\/OAuth2\/ResponseType\/CodeResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]],["ResponseTypeHandlerFactory","AuthBucket\/OAuth2\/ResponseType\/ResponseTypeHandlerFactory.html","",
                [        ]],["ResponseTypeHandlerFactoryInterface","AuthBucket\/OAuth2\/ResponseType\/ResponseTypeHandlerFactoryInterface.html","",
                [        ]],["ResponseTypeHandlerInterface","AuthBucket\/OAuth2\/ResponseType\/ResponseTypeHandlerInterface.html","",
                [        ]],["TokenResponseTypeHandler","AuthBucket\/OAuth2\/ResponseType\/TokenResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]]        ]],["Security",,"",
                [["Authentication",,"",
                [["Provider","AuthBucket\/OAuth2\/Security\/Authentication\/Provider.html","",
                [["ResourceProvider","AuthBucket\/OAuth2\/Security\/Authentication\/Provider\/ResourceProvider.html","",
                [        ]],["TokenProvider","AuthBucket\/OAuth2\/Security\/Authentication\/Provider\/TokenProvider.html","",
                [        ]]        ]],["Token","AuthBucket\/OAuth2\/Security\/Authentication\/Token.html","",
                [["AccessToken","AuthBucket\/OAuth2\/Security\/Authentication\/Token\/AccessToken.html"," < AbstractToken",
                [        ]],["ClientToken","AuthBucket\/OAuth2\/Security\/Authentication\/Token\/ClientToken.html"," < AbstractToken",
                [        ]]        ]]        ]],["Firewall","AuthBucket\/OAuth2\/Security\/Firewall.html","",
                [["ResourceListener","AuthBucket\/OAuth2\/Security\/Firewall\/ResourceListener.html","",
                [        ]],["TokenListener","AuthBucket\/OAuth2\/Security\/Firewall\/TokenListener.html","",
                [        ]]        ]]        ]],["TokenType","AuthBucket\/OAuth2\/TokenType.html","",
                [["BearerTokenTypeHandler","AuthBucket\/OAuth2\/TokenType\/BearerTokenTypeHandler.html","",
                [        ]],["MacTokenTypeHandler","AuthBucket\/OAuth2\/TokenType\/MacTokenTypeHandler.html","",
                [        ]],["TokenTypeHandlerFactory","AuthBucket\/OAuth2\/TokenType\/TokenTypeHandlerFactory.html","",
                [        ]],["TokenTypeHandlerFactoryInterface","AuthBucket\/OAuth2\/TokenType\/TokenTypeHandlerFactoryInterface.html","",
                [        ]],["TokenTypeHandlerInterface","AuthBucket\/OAuth2\/TokenType\/TokenTypeHandlerInterface.html","",
                [        ]]        ]],["Util","AuthBucket\/OAuth2\/Util.html","",
                [["Filter","AuthBucket\/OAuth2\/Util\/Filter.html","",
                [        ]],["JsonResponse","AuthBucket\/OAuth2\/Util\/JsonResponse.html"," < JsonResponse",
                [        ]],["RedirectResponse","AuthBucket\/OAuth2\/Util\/RedirectResponse.html"," < RedirectResponse",
                [        ]]        ]]        ]]        ]],["Pantarei",,"",
                [["OAuth2",,"",
                [["Controller","Pantarei\/OAuth2\/Controller.html","",
                [["AuthorizeController","Pantarei\/OAuth2\/Controller\/AuthorizeController.html","",
                [        ]],["ResourceController","Pantarei\/OAuth2\/Controller\/ResourceController.html","",
                [        ]],["TokenController","Pantarei\/OAuth2\/Controller\/TokenController.html","",
                [        ]]        ]],["EventListener","Pantarei\/OAuth2\/EventListener.html","",
                [["ExceptionListener","Pantarei\/OAuth2\/EventListener\/ExceptionListener.html","",
                [        ]]        ]],["Exception","Pantarei\/OAuth2\/Exception.html","",
                [["AccessDeniedException","Pantarei\/OAuth2\/Exception\/AccessDeniedException.html"," < LogicException",
                [        ]],["ExceptionInterface","Pantarei\/OAuth2\/Exception\/ExceptionInterface.html","",
                [        ]],["InvalidClientException","Pantarei\/OAuth2\/Exception\/InvalidClientException.html"," < InvalidArgumentException",
                [        ]],["InvalidGrantException","Pantarei\/OAuth2\/Exception\/InvalidGrantException.html"," < InvalidArgumentException",
                [        ]],["InvalidRequestException","Pantarei\/OAuth2\/Exception\/InvalidRequestException.html"," < InvalidArgumentException",
                [        ]],["InvalidScopeException","Pantarei\/OAuth2\/Exception\/InvalidScopeException.html"," < InvalidArgumentException",
                [        ]],["ServerErrorException","Pantarei\/OAuth2\/Exception\/ServerErrorException.html"," < LogicException",
                [        ]],["TemporarilyUnavailableException","Pantarei\/OAuth2\/Exception\/TemporarilyUnavailableException.html"," < LogicException",
                [        ]],["UnauthorizedClientException","Pantarei\/OAuth2\/Exception\/UnauthorizedClientException.html"," < LogicException",
                [        ]],["UnsupportedGrantTypeException","Pantarei\/OAuth2\/Exception\/UnsupportedGrantTypeException.html"," < InvalidArgumentException",
                [        ]],["UnsupportedResponseTypeException","Pantarei\/OAuth2\/Exception\/UnsupportedResponseTypeException.html"," < InvalidArgumentException",
                [        ]]        ]],["GrantType","Pantarei\/OAuth2\/GrantType.html","",
                [["AbstractGrantTypeHandler","Pantarei\/OAuth2\/GrantType\/AbstractGrantTypeHandler.html","",
                [        ]],["AuthorizationCodeGrantTypeHandler","Pantarei\/OAuth2\/GrantType\/AuthorizationCodeGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["ClientCredentialsGrantTypeHandler","Pantarei\/OAuth2\/GrantType\/ClientCredentialsGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["GrantTypeHandlerFactory","Pantarei\/OAuth2\/GrantType\/GrantTypeHandlerFactory.html","",
                [        ]],["GrantTypeHandlerFactoryInterface","Pantarei\/OAuth2\/GrantType\/GrantTypeHandlerFactoryInterface.html","",
                [        ]],["GrantTypeHandlerInterface","Pantarei\/OAuth2\/GrantType\/GrantTypeHandlerInterface.html","",
                [        ]],["PasswordGrantTypeHandler","Pantarei\/OAuth2\/GrantType\/PasswordGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]],["RefreshTokenGrantTypeHandler","Pantarei\/OAuth2\/GrantType\/RefreshTokenGrantTypeHandler.html"," < AbstractGrantTypeHandler",
                [        ]]        ]],["Model","Pantarei\/OAuth2\/Model.html","",
                [["AccessTokenInterface","Pantarei\/OAuth2\/Model\/AccessTokenInterface.html","",
                [        ]],["AccessTokenManagerInterface","Pantarei\/OAuth2\/Model\/AccessTokenManagerInterface.html","",
                [        ]],["AuthorizeInterface","Pantarei\/OAuth2\/Model\/AuthorizeInterface.html","",
                [        ]],["AuthorizeManagerInterface","Pantarei\/OAuth2\/Model\/AuthorizeManagerInterface.html","",
                [        ]],["ClientInterface","Pantarei\/OAuth2\/Model\/ClientInterface.html","",
                [        ]],["ClientManagerInterface","Pantarei\/OAuth2\/Model\/ClientManagerInterface.html","",
                [        ]],["CodeInterface","Pantarei\/OAuth2\/Model\/CodeInterface.html","",
                [        ]],["CodeManagerInterface","Pantarei\/OAuth2\/Model\/CodeManagerInterface.html","",
                [        ]],["ModelInterface","Pantarei\/OAuth2\/Model\/ModelInterface.html","",
                [        ]],["ModelManagerFactoryInterface","Pantarei\/OAuth2\/Model\/ModelManagerFactoryInterface.html","",
                [        ]],["ModelManagerInterface","Pantarei\/OAuth2\/Model\/ModelManagerInterface.html","",
                [        ]],["RefreshTokenInterface","Pantarei\/OAuth2\/Model\/RefreshTokenInterface.html","",
                [        ]],["RefreshTokenManagerInterface","Pantarei\/OAuth2\/Model\/RefreshTokenManagerInterface.html","",
                [        ]],["ScopeInterface","Pantarei\/OAuth2\/Model\/ScopeInterface.html","",
                [        ]],["ScopeManagerInterface","Pantarei\/OAuth2\/Model\/ScopeManagerInterface.html","",
                [        ]]        ]],["Provider","Pantarei\/OAuth2\/Provider.html","",
                [["OAuth2ServiceProvider","Pantarei\/OAuth2\/Provider\/OAuth2ServiceProvider.html","",
                [        ]]        ]],["ResponseType","Pantarei\/OAuth2\/ResponseType.html","",
                [["AbstractResponseTypeHandler","Pantarei\/OAuth2\/ResponseType\/AbstractResponseTypeHandler.html","",
                [        ]],["CodeResponseTypeHandler","Pantarei\/OAuth2\/ResponseType\/CodeResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]],["ResponseTypeHandlerFactory","Pantarei\/OAuth2\/ResponseType\/ResponseTypeHandlerFactory.html","",
                [        ]],["ResponseTypeHandlerFactoryInterface","Pantarei\/OAuth2\/ResponseType\/ResponseTypeHandlerFactoryInterface.html","",
                [        ]],["ResponseTypeHandlerInterface","Pantarei\/OAuth2\/ResponseType\/ResponseTypeHandlerInterface.html","",
                [        ]],["TokenResponseTypeHandler","Pantarei\/OAuth2\/ResponseType\/TokenResponseTypeHandler.html"," < AbstractResponseTypeHandler",
                [        ]]        ]],["Security",,"",
                [["Authentication",,"",
                [["Provider","Pantarei\/OAuth2\/Security\/Authentication\/Provider.html","",
                [["ResourceProvider","Pantarei\/OAuth2\/Security\/Authentication\/Provider\/ResourceProvider.html","",
                [        ]],["TokenProvider","Pantarei\/OAuth2\/Security\/Authentication\/Provider\/TokenProvider.html","",
                [        ]]        ]],["Token","Pantarei\/OAuth2\/Security\/Authentication\/Token.html","",
                [["AccessToken","Pantarei\/OAuth2\/Security\/Authentication\/Token\/AccessToken.html"," < AbstractToken",
                [        ]],["ClientToken","Pantarei\/OAuth2\/Security\/Authentication\/Token\/ClientToken.html"," < AbstractToken",
                [        ]]        ]]        ]],["Firewall","Pantarei\/OAuth2\/Security\/Firewall.html","",
                [["ResourceListener","Pantarei\/OAuth2\/Security\/Firewall\/ResourceListener.html","",
                [        ]],["TokenListener","Pantarei\/OAuth2\/Security\/Firewall\/TokenListener.html","",
                [        ]]        ]]        ]],["TokenType","Pantarei\/OAuth2\/TokenType.html","",
                [["BearerTokenTypeHandler","Pantarei\/OAuth2\/TokenType\/BearerTokenTypeHandler.html","",
                [        ]],["MacTokenTypeHandler","Pantarei\/OAuth2\/TokenType\/MacTokenTypeHandler.html","",
                [        ]],["TokenTypeHandlerFactory","Pantarei\/OAuth2\/TokenType\/TokenTypeHandlerFactory.html","",
                [        ]],["TokenTypeHandlerFactoryInterface","Pantarei\/OAuth2\/TokenType\/TokenTypeHandlerFactoryInterface.html","",
                [        ]],["TokenTypeHandlerInterface","Pantarei\/OAuth2\/TokenType\/TokenTypeHandlerInterface.html","",
                [        ]]        ]],["Util","Pantarei\/OAuth2\/Util.html","",
                [["Filter","Pantarei\/OAuth2\/Util\/Filter.html","",
                [        ]],["JsonResponse","Pantarei\/OAuth2\/Util\/JsonResponse.html"," < JsonResponse",
                [        ]],["RedirectResponse","Pantarei\/OAuth2\/Util\/RedirectResponse.html"," < RedirectResponse",
                [        ]]        ]]        ]]        ]]        ]

